<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ConsulTransactionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('consul_transactions')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('consul_transactions')->insert([
            [
                'id' => '1',
                'payment_number' => 'CS-241128R73O1',
                'user_id' => '12',
                'consultation_id' => '1',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '100000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 02:05:20',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '2',
                'payment_number' => 'CS-2411288E5B2',
                'user_id' => '12',
                'consultation_id' => '2',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '300000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 02:43:38',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '3',
                'payment_number' => 'CS-241128IIHX3',
                'user_id' => '12',
                'consultation_id' => '3',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '300000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 03:25:09',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '4',
                'payment_number' => 'CS-241128FPLN4',
                'user_id' => '12',
                'consultation_id' => '4',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 03:32:36',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '5',
                'payment_number' => 'CS-241128XYOG5',
                'user_id' => '12',
                'consultation_id' => '5',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 03:34:47',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '6',
                'payment_number' => 'CS-241128WKBP6',
                'user_id' => '12',
                'consultation_id' => '6',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '100000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 03:41:19',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '7',
                'payment_number' => 'CS-241128LHCH7',
                'user_id' => '12',
                'consultation_id' => '7',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 04:05:08',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '8',
                'payment_number' => 'CS-24112841IW8',
                'user_id' => '12',
                'consultation_id' => '8',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '100000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 04:06:23',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '9',
                'payment_number' => 'CS-241128ZHFF9',
                'user_id' => '12',
                'consultation_id' => '9',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '300000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 04:12:37',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '10',
                'payment_number' => 'CS-2411281UVY10',
                'user_id' => '12',
                'consultation_id' => '10',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 04:14:27',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '11',
                'payment_number' => 'CS-241128XBHH11',
                'user_id' => '12',
                'consultation_id' => '11',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/omOslaRBG548lOJbgBIurMkTnbYMFBjlZBhxoPb3.png',
                'sender_name' => 'Tono Hartono',
                'sender_bank' => 'Bank BSI',
                'status' => 'pending_confirmation',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-11-29 08:53:21',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-28 04:19:49',
                'updated_at' => '2024-11-29 08:53:21',
            ],
            [
                'id' => '12',
                'payment_number' => 'CS-241129VPQI12',
                'user_id' => '12',
                'consultation_id' => '12',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '300000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-29 02:17:21',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '13',
                'payment_number' => 'CS-241129MUW813',
                'user_id' => '12',
                'consultation_id' => '13',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '300000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-29 03:15:58',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '14',
                'payment_number' => 'CS-241129JHJE14',
                'user_id' => '12',
                'consultation_id' => '14',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '300000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => 'storage/payment_proofs/wXZcAGLHfJIRnJa6Of97rbelYaqaqZZpv14Ypj7Z.png',
                'sender_name' => 'Tono Hartono',
                'sender_bank' => 'Bank BSI',
                'status' => 'completed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-11-29 08:00:11',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-29 03:19:56',
                'updated_at' => '2024-12-14 04:45:31',
            ],
            [
                'id' => '15',
                'payment_number' => 'CS-2411306J9X15',
                'user_id' => '12',
                'consultation_id' => '15',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/mqQKqDhZIpkpgEdjzo3pYV6zquqKlbIxBvx3XtrC.jpg',
                'sender_name' => 'neli',
                'sender_bank' => 'NELIE',
                'status' => 'pending_confirmation',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-11-30 02:31:07',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-30 01:50:24',
                'updated_at' => '2024-11-30 02:31:07',
            ],
            [
                'id' => '16',
                'payment_number' => 'CS-241130MGHF16',
                'user_id' => '12',
                'consultation_id' => '16',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/KW2PANjrnqmPiy2FG2euggddcHkLP5wOD0qrAqBW.jpg',
                'sender_name' => 'saya',
                'sender_bank' => 'saya',
                'status' => 'pending_confirmation',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-11-30 02:58:37',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-30 02:50:06',
                'updated_at' => '2024-11-30 02:58:37',
            ],
            [
                'id' => '17',
                'payment_number' => 'CS-241130NHYU17',
                'user_id' => '12',
                'consultation_id' => '17',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-11-30 04:10:53',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '18',
                'payment_number' => 'CS-241202BYBA18',
                'user_id' => '12',
                'consultation_id' => '18',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/IbUNTNrnYNaLucd9qx06T7rIiT89h8dG87EV5Hq0.jpg',
                'sender_name' => 'neli',
                'sender_bank' => 'NELIA',
                'status' => 'completed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-12-02 02:13:46',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-02 01:45:31',
                'updated_at' => '2024-12-07 05:29:20',
            ],
            [
                'id' => '19',
                'payment_number' => 'CS-241202STH519',
                'user_id' => '12',
                'consultation_id' => '19',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '300000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/9guPK4CYXsTshG2UUkEz2IFaA4VoitTsly3kTSP3.jpg',
                'sender_name' => 'eli',
                'sender_bank' => 'neli',
                'status' => 'completed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-12-02 03:20:49',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-02 03:20:03',
                'updated_at' => '2024-12-14 04:40:35',
            ],
            [
                'id' => '20',
                'payment_number' => 'CS-241202M8VL20',
                'user_id' => '12',
                'consultation_id' => '20',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => 'storage/payment_proofs/Nmw4TMTIhig3QL6cHa4GLnwln3bc6zo19EpNtpgj.jpg',
                'sender_name' => 'aya',
                'sender_bank' => 'aya',
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-12-02 07:25:45',
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-02 07:22:24',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '21',
                'payment_number' => 'CS-2412039BJ321',
                'user_id' => '12',
                'consultation_id' => '21',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/CjaP1OyMrOqzWKNURbRQzrMcxDBXVZF3D3F592Hb.jpg',
                'sender_name' => 'ui',
                'sender_bank' => 'ui',
                'status' => 'completed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-12-03 01:29:33',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-03 01:28:34',
                'updated_at' => '2024-12-03 01:45:16',
            ],
            [
                'id' => '22',
                'payment_number' => 'CS-2412048LSB22',
                'user_id' => '12',
                'consultation_id' => '22',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '100000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-04 08:31:58',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '23',
                'payment_number' => 'CS-241211ITNP23',
                'user_id' => '12',
                'consultation_id' => '23',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-11 02:26:50',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '24',
                'payment_number' => 'CS-241211CTJS24',
                'user_id' => '12',
                'consultation_id' => '24',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-11 02:43:07',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '25',
                'payment_number' => 'CS-241212J7EX25',
                'user_id' => '12',
                'consultation_id' => '25',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '400000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'failed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => 'Batas waktu pembayaran telah selesai',
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-12 03:10:55',
                'updated_at' => '2024-12-14 03:47:01',
            ],
            [
                'id' => '26',
                'payment_number' => 'CS-241213C1KN26',
                'user_id' => '12',
                'consultation_id' => '26',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '200000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/qpw9ze5ZcR91tqYOabIKBvluC1Zp2TCpgU70VZIx.jpg',
                'sender_name' => 'tes',
                'sender_bank' => 'tes',
                'status' => 'completed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-12-13 07:30:54',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-13 07:30:21',
                'updated_at' => '2024-12-13 07:31:44',
            ],
            [
                'id' => '27',
                'payment_number' => 'CS-2412145HVH27',
                'user_id' => '12',
                'consultation_id' => '27',
                'voucher_id' => null,
                'payment_method_id' => '2',
                'consul_fee' => '400000.00',
                'discount_amount' => '0.00',
                'payment_proof' => 'storage/payment_proofs/DxCjS2RiEvAObA8L1rVvolUfQo1mOmk6sz8THLAs.png',
                'sender_name' => 'hernan',
                'sender_bank' => 'bsi',
                'status' => 'completed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-12-14 03:29:59',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-14 03:29:32',
                'updated_at' => '2024-12-14 03:35:34',
            ],
            [
                'id' => '28',
                'payment_number' => 'CS-241215-RFYJ0E',
                'user_id' => '12',
                'consultation_id' => '31',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '900000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => null,
                'sender_name' => null,
                'sender_bank' => null,
                'status' => 'pending',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => null,
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-15 03:33:58',
                'updated_at' => '2024-12-15 03:33:58',
            ],
            [
                'id' => '29',
                'payment_number' => 'CS-241216-8ZYYZ4',
                'user_id' => '12',
                'consultation_id' => '32',
                'voucher_id' => '3',
                'payment_method_id' => '2',
                'consul_fee' => '400000.00',
                'discount_amount' => '20000.00',
                'payment_proof' => 'storage/payment_proofs/Qzi2Bi1HdWaSHUHxXdU40q50RGrGGqQFiv0s5q1J.jpg',
                'sender_name' => 'Neli Fauziyah',
                'sender_bank' => 'Bank Mandiri',
                'status' => 'completed',
                'transaction_reference' => null,
                'payment_gateway_response' => null,
                'payment_expiration' => null,
                'payment_completed_at' => '2024-12-16 04:17:43',
                'failure_reason' => null,
                'commission_transfer_status' => 'Menunggu Konfirmasi',
                'commission_transfer_proof' => null,
                'created_at' => '2024-12-16 03:55:08',
                'updated_at' => '2024-12-16 04:26:02',
            ],
        ]);
    }
}
